version: '3'

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
    depends_on:
      - php
    environment:
      TZ: ${WORKSPACE_TIMEZONE}

  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
      args:
        TZ: ${WORKSPACE_TIMEZONE}
    container_name: php
    volumes:
      - .:/var/www
    ports:
      - "${PHP_PORT}:9000"
